---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: debian-9
  - name: centos-7
  - name: fedora-26

suites:
  - name: default
    run_list:
      - recipe[redis_test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
      attrs:
        - test/smoke/default/files/instances.yml
    attributes:
